import Head from 'next/head'
import Sidebar from '../components/Sidebar';
import styled from "styled-components";


export default function Home() {
  return (
    <Container>
      <Head>
        <title>WhatsApp AdheCode</title>
        <meta name="description" content="Generated by AdheCode" />
        <link rel="icon" href="./580b57fcd9996e24bc43c543.png" type="image/gif" sizes="16x16"></link>
      </Head>
      <Sidebar />
      <ChatContainer>
        <Logo src="./up0ouh31JCcugh9CiA.png" />
      </ChatContainer>
    </Container>
  )
}

const Container = styled.div`
    display: flex;
    padding-left:10%;
    padding-right:10%;
    padding-top:1%;
    background: linear-gradient(#128C7E 50%, #dcdcdc 50%);
`;

const ChatContainer = styled.div`
    flex: 1;
    background-color:#f8f9fa;
`;

const Logo = styled.img`
    height: 80%;
    width: 100%;
`;
