import styled from 'styled-components';
import Head from 'next/head';
import { Button } from "@material-ui/core";
import {auth, provider} from '../firebase';

function Login() {
    const signIn = () => {
        auth.signInWithPopup(provider).catch(alert)
    }

    return (
        <Container>
            <Head>
                <title>WhatsApp by AdheCode</title>
                <meta name="description" content="Generated by AdheCode" />
                <link rel="icon" href="./580b57fcd9996e24bc43c543.png" type="image/gif" sizes="16x16"></link>
            </Head>
            <LoginContainer>
                <Logo src="https://assets.stickpng.com/images/580b57fcd9996e24bc43c543.png" />
                <Button onClick={signIn} variant="outlined">Sign in with Google</Button>
            </LoginContainer>
        </Container>
    )
}

export default Login;

const Container = styled.div`
    display: grid;
    place-items: center;
    height:100vh;
    background: linear-gradient(#128C7E 50%, #dcdcdc 50%);
`;
const LoginContainer = styled.div`
    padding: 100px;
    align-items: center;
    display: flex;
    flex-direction: column;
    background-color:white;
    border-radius:5px;
    box-shadow: 0px 4px 14px -3px rgba(0,0,0,0.7);
`;
const Logo = styled.img`
    height: 200px;
    width: 200px;
    margin-bottom: 50px;
`;
